# Generated by Django 2.1.1 on 2019-02-06 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='IaaS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaas_name', models.TextField(max_length=120)),
                ('iaas_ip', models.TextField(max_length=120)),
                ('iaas_state', models.TextField(blank=True, max_length=120, null=True)),
                ('iaas_configuration', models.TextField(blank=True, max_length=120, null=True)),
                ('iaas_date_discovery', models.DateTimeField(default=datetime.datetime.now)),
                ('iaas_date_configuration', models.DateTimeField(default=datetime.datetime.now)),
                ('iaas_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IaaSConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaas_cpu', models.IntegerField()),
                ('iaas_ram', models.IntegerField()),
                ('iaas_disk', models.FloatField()),
                ('iaas_time', models.DateTimeField(default=datetime.datetime.now)),
                ('iaas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.IaaS')),
            ],
        ),
        migrations.CreateModel(
            name='IpsPorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(max_length=120)),
                ('port', models.IntegerField()),
                ('usage', models.IntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.TextField(max_length=120)),
                ('result', models.TextField(max_length=50)),
                ('code', models.TextField(max_length=120)),
                ('client_name', models.TextField(max_length=120)),
                ('token', models.TextField(max_length=120)),
                ('usage', models.TextField(max_length=120)),
                ('iaas', models.TextField(default='None', max_length=120)),
                ('cpu', models.TextField(default='1', max_length=120)),
                ('ram', models.TextField(default='512M', max_length=120)),
                ('application_type', models.TextField(default='video', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_time', models.DateTimeField(default=datetime.datetime.now)),
                ('cpu_data', models.IntegerField()),
                ('ram_data', models.IntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.Container')),
            ],
        ),
        migrations.CreateModel(
            name='OverlayInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.TextField(max_length=120)),
                ('trigger_action', models.TextField(default='api_call', max_length=120)),
                ('trigger_time', models.DateTimeField(default=datetime.datetime.now)),
                ('trigger_result', models.TextField(max_length=120, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.Container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='iaas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.IaaS'),
        ),
    ]
