# Generated by Django 2.1.5 on 2019-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iaas',
            old_name='iaas',
            new_name='iaas_name',
        ),
        migrations.AlterField(
            model_name='container',
            name='ip_address',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
