# Generated by Django 2.1.5 on 2019-02-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_name',
            field=models.TextField(max_length=120, unique=True),
        ),
    ]
