# Generated by Django 2.1.1 on 2019-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iaasconsumption',
            options={'ordering': ['-iaas_time']},
        ),
        migrations.AlterField(
            model_name='iaas',
            name='iaas_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
